### ISSUE TITLE
Can't get colab pro to run mega

### ISSUE THREAD

**Issue by F1r3Hydr4nt** [saharmor/dalle-playground#20]
Any ideas? I also tried 16fp too

**Comment by DigitalDwagon** [comment]
What exactly is the error?

**Comment by F1r3Hydr4nt** [comment]
RESOURCE_EXHAUSTION it was trying to allocate something like 40GB
```bash
wandb: Downloading large artifact mega-1-fp16:latest, 4938.53MB. 7 files... Done. 0:0:0
tcmalloc: large alloc 5175050240 bytes == 0x43ca2000 @  0x7f4cc97c61e7 0x4a3940 0x5b438c 0x5ea94f 0x5939cb 0x594cd3 0x5d0ecb 0x59aeca 0x515655 0x549e0e 0x4bca8a 0x59c019 0x595ef6 0x5134a6 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f4cc93c3c87 0x5b621a
2022-06-08 02:00:41.026674: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 384.00MiB (rounded to 402653184)requested by op 
2022-06-08 02:00:41.026936: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:491] ***************************************************************************************************_
Traceback (most recent call last):
  File "dalle-playground/backend/app.py", line 57, in <module>
    model = DalleBart.from_pretrained(DALLE_MODEL, revision=DALLE_COMMIT_ID)
  File "/usr/local/lib/python3.7/dist-packages/dalle_mini/model/utils.py", line 26, in from_pretrained
    pretrained_model_name_or_path, *model_args, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_flax_utils.py", line 621, in from_pretrained
    state = jax.tree_util.tree_map(jnp.array, state)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py", line 184, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py", line 184, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/numpy/lax_numpy.py", line 1868, in array
    out = lax_internal._convert_element_type(out, dtype, weak_type=weak_type)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lax/lax.py", line 522, in _convert_element_type
    weak_type=new_weak_type)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 325, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 328, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 678, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 98, in apply_primitive
    return compiled_fun(*args)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 118, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 591, in _execute_trivial
    else h(*device_put(x, device)) for h, x in zip(handlers, outs)]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 591, in <listcomp>
    else h(*device_put(x, device)) for h, x in zip(handlers, outs)]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 793, in device_put
    return device_put_handlers[type(x)](x, device)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 804, in _device_put_array
    return (backend.buffer_from_pyval(x, device),)
RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 402653184 bytes```

**Comment by DigitalDwagon** [comment]
Yeah that's really strange. Not sure what to help with there, sorry

**Comment by F1r3Hydr4nt** [comment]
Have you manage to get the larger data sets to run on colab+/pro? Or
anybody else?

**Comment by devn** [comment]
I'm in the same boat. Upgraded to Colab Pro+ and no dice:

```log
wandb: Downloading large artifact mega-1:latest, 9873.84MB. 7 files... Done. 0:0:0
tcmalloc: large alloc 10350092288 bytes == 0x7f917195e000 @  0x7f991c15f1e7 0x4a3940 0x5b438c 0x5ea94f 0x5939cb 0x594cd3 0x5d0ecb 0x59aeca 0x515655 0x549e0e 0x4bca8a 0x59c019 0x595ef6 0x5134a6 0x549e0e 0x593fce 0x548ae9 0x5127f1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f991bd5cc87 0x5b621a
2022-06-08 17:57:27.421243: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 768.00MiB (rounded to 805306368)requested by op 
2022-06-08 17:57:27.422646: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:491] **************************************************************************************************__
Traceback (most recent call last):
  File "dalle-playground/backend/app.py", line 55, in <module>
    model = DalleBart.from_pretrained(DALLE_MODEL, revision=DALLE_COMMIT_ID)
  File "/usr/local/lib/python3.7/dist-packages/dalle_mini/model/utils.py", line 26, in from_pretrained
    pretrained_model_name_or_path, *model_args, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_flax_utils.py", line 621, in from_pretrained
    state = jax.tree_util.tree_map(jnp.array, state)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py", line 184, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py", line 184, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/numpy/lax_numpy.py", line 1868, in array
    out = lax_internal._convert_element_type(out, dtype, weak_type=weak_type)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/lax/lax.py", line 522, in _convert_element_type
    weak_type=new_weak_type)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 325, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 328, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 678, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 98, in apply_primitive
    return compiled_fun(*args)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 118, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 591, in _execute_trivial
    else h(*device_put(x, device)) for h, x in zip(handlers, outs)]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 591, in <listcomp>
    else h(*device_put(x, device)) for h, x in zip(handlers, outs)]
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 793, in device_put
    return device_put_handlers[type(x)](x, device)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 804, in _device_put_array
    return (backend.buffer_from_pyval(x, device),)
RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 805306368 bytes.
```

**Comment by danielchalef** [comment]
Try using a newer version of `transformers` and modify `from_pretrained` to not init the model using `_do_init=False`. See the PR I submitted here: https://github.com/saharmor/dalle-playground/pull/26

**Comment by F1r3Hydr4nt** [comment]
Thank you that worked for mega also. Now to incorporate [this flow](https://github.com/jina-ai/dalle-flow) somehow, thanks!

**Comment by F1r3Hydr4nt** [comment]
You are running the larger one, try the 16f and see what happens
