### ISSUE TITLE
No module named wandb

### ISSUE THREAD

**Issue by CorkCoin** [saharmor/dalle-playground#5]

**Comment by CorkCoin** [comment]
Installed and imported wandb,

now I get this error

`Traceback (most recent call last):
  File "dalle-playground/backend/app.py", line 9, in <module>
    from dalle_mini.model import CustomFlaxBartForConditionalGeneration
ImportError: cannot import name 'CustomFlaxBartForConditionalGeneration' from 'dalle_mini.model' (/usr/local/lib/python3.7/dist-packages/dalle_mini/model/__init__.py)`

**Comment by Hamdan85** [comment]
Im having something similar:

Traceback (most recent call last):
  File "dalle-playground/backend/app.py", line 9, in <module>
    from dalle_mini.model import CustomFlaxBartForConditionalGeneration
  File "/usr/local/lib/python3.7/dist-packages/dalle_mini/__init__.py", line 3, in <module>
    from .model import DalleBart, DalleBartProcessor
  File "/usr/local/lib/python3.7/dist-packages/dalle_mini/model/__init__.py", line 2, in <module>
    from .modeling import DalleBart
  File "/usr/local/lib/python3.7/dist-packages/dalle_mini/model/modeling.py", line 31, in <module>
    from flax.linen import partitioning as nn_partitioning
ImportError: cannot import name 'partitioning' from 'flax.linen' (/usr/local/lib/python3.7/dist-packages/flax/linen/__init__.py)

**Comment by saharmor** [comment]
Hey everyone and thanks for flagging this. The error was due to me wrongly anchoring to an old version of Flax which was incompatible with DALL-E Mini. Should work now.
Please reopen should the issue persist. Thanks!

**Comment by Vixxd** [comment]
Hi there, I am also having an issue with Flax when trying to start the server (Windows 11):

`C:\Users\me\FunDev\dalle-playground\backend>python app.py 8080
--> Starting DALL-E Server. This might take up to two minutes.
Traceback (most recent call last):
  File "C:\Users\me\FunDev\dalle-playground\backend\app.py", line 13, in <module>
    from dalle_model import DalleModel
  File "C:\Users\me\FunDev\dalle-playground\backend\dalle_model.py", line 11, in <module>
    from dalle_mini import DalleBart, DalleBartProcessor
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dalle_mini\__init__.py", line 3, in <module>
    from .model import DalleBart, DalleBartProcessor
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dalle_mini\model\__init__.py", line 2, in <module>
    from .modeling import DalleBart
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dalle_mini\model\modeling.py", line 28, in <module>
    from flax.linen import partitioning as nn_partitioning
ImportError: cannot import name 'partitioning' from 'flax.linen' (C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flax\linen\__init__.py)`

I have the version of jaxlib from this URL installed: 
- https://whls.blob.core.windows.net/unstable/cpu/jaxlib-0.1.76-cp310-none-win_amd64.whl 

And:
- Windows 11
- Cuda 11.7
- Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32

Let me know if you need any further information - I know my way around terminal & package managers but it's been a while since I've done something like this and I've hit a bit of a brick wall in trying to run the DALL-E playground locally :)

**Comment by raylin01** [comment]
Having same issue, I've been trying Jax==0.3.5 as referenced in #3 , let me know if you find a solution
