### ISSUE TITLE
Mega model incomplete input error

### ISSUE THREAD

**Issue by lugia19** [saharmor/dalle-playground#60]
Whenever I try running the mega model, I get this error:
```
Traceback (most recent call last):

  File "app.py", line 47, in <module>

    dalle_model = DalleModel(dalle_version)

  File "/app/dalle_model.py", line 62, in __init__

    self.model, params = DalleBart.from_pretrained(

  File "/usr/local/lib/python3.8/dist-packages/dalle_mini/model/utils.py", line 25, in from_pretrained

    return super(PretrainedFromWandbMixin, cls).from_pretrained(

  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_flax_utils.py", line 603, in from_pretrained

    state = from_bytes(cls, state_f.read())

  File "/usr/local/lib/python3.8/dist-packages/flax/serialization.py", line 368, in from_bytes

    state_dict = msgpack_restore(encoded_bytes)

  File "/usr/local/lib/python3.8/dist-packages/flax/serialization.py", line 350, in msgpack_restore

    state_dict = msgpack.unpackb(

  File "msgpack/_unpacker.pyx", line 205, in msgpack._cmsgpack.unpackb

ValueError: Unpack failed: incomplete input

```
Any fix?

**Comment by saharmor** [comment]
How do you run the playground? Through the linked notebook in the repository? Any further information will help in resolving your issue.

**Comment by lugia19** [comment]
Sorry, forgot to include the details. I'm using the docker container on windows. I've got an rtx 3080. CUDA acceleration is set up correctly and all.

**Comment by BBaoVanC** [comment]
I'm getting the same issue, I also tried using the `docker-compose.yaml` in this repo. I have nvidia-docker set up properly too, and it works in other projects for me.
