### ISSUE TITLE
Cannot install flax because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by pr1ntr** [saharmor/dalle-playground#65]
```
ERROR: Cannot install flax because these package versions have conflicting dependencies.

The conflict is caused by:
    optax 0.1.2 depends on jaxlib>=0.1.37
    optax 0.1.1 depends on jaxlib>=0.1.37
    optax 0.1.0 depends on jaxlib>=0.1.37
    optax 0.0.91 depends on jaxlib>=0.1.37
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37
    optax 0.0.5 depends on jaxlib>=0.1.37
    optax 0.0.3 depends on jaxlib>=0.1.37
    optax 0.0.2 depends on jaxlib>=0.1.37
    optax 0.0.1 depends on jaxlib>=0.1.37
```

WIn 11
Python 3.10.5
PIP 22.0.4

**Comment by Phildo** [comment]
Same:

```
ERROR: Cannot install -r requirements.txt (line 4), flax and transformers because these package versions have conflicting dependencies.                                                                                                                                                                                                                                                                                                                                                             The conflict is caused by:                                                                                                                                                                                                                            optax 0.1.2 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.1.1 depends on jaxlib>=0.1.37                                                                                                                                                                                                             flax 0.5.0 depends on typing-extensions>=4.1.1                                                                                                                                                                                                    huggingface-hub 0.1.0 depends on typing-extensions                                                                                                                                                                                                jax 0.3.0 depends on typing_extensions                                                                                                                                                                                                            optax 0.1.0 depends on typing-extensions~=3.10.0                                                                                                                                                                                                  flax 0.5.0 depends on typing-extensions>=4.1.1                                                                                                                                                                                                    huggingface-hub 0.1.0 depends on typing-extensions                                                                                                                                                                                                jax 0.3.0 depends on typing_extensions                                                                                                                                                                                                            optax 0.0.91 depends on typing-extensions~=3.10.0                                                                                                                                                                                                 optax 0.0.9 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.8 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.6 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.5 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.3 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.2 depends on jaxlib>=0.1.37                                                                                                                                                                                                             optax 0.0.1 depends on jaxlib>=0.1.37                                                                                                                                                                                                                                                                                                                                                                                                                                                           To fix this you could try to:                                                                                                                                                                                                                     1. loosen the range of package versions you've specified                                                                                                                                                                                          2. remove package versions to allow pip attempt to solve the dependency conflict                                                                                                                                                                                                                                                                                                                                                                                                                    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by dmwyatt** [comment]
I managed to get it installed in WSL2 instead of straight on Windows.

**Comment by Phildo** [comment]
> Had to get cuda toolkit, cudnn, troubleshooting issues and stuff...but it's working great in WSL2.

installed WSL2, cuda toolkit, and cudnn. getting a bunch of errors booting up mega, the first of which being:

`
--> Starting DALL-E Server. This might take up to two minutes.                                                                                                                                                                                       Traceback (most recent call last):

File "/home/phildo/.local/lib/python3.8/site-packages/dalle_mini/model/utils.py", line 23, in from_pretrained
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 3885, in download
File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 3979, in _download_file
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 3355, in download
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 912, in load_file
File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/sdk/interface/artifacts.py", line 948, in helper
File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
File "/home/phildo/.local/lib/python3.8/site-packages/wandb/util.py", line 1430, in fsync_open
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:
`
(then a bunch more errors)

**Comment by SantinoPetrovic** [comment]
Having the same issue:

`ERROR: Cannot install -r requirements.txt (line 4), flax and transformers because these package versions have conflicting dependencies.

The conflict is caused by:
    optax 0.1.2 depends on jaxlib>=0.1.37
    optax 0.1.1 depends on jaxlib>=0.1.37
    flax 0.5.0 depends on typing-extensions>=4.1.1
    huggingface-hub 0.1.0 depends on typing-extensions
    jax 0.3.0 depends on typing_extensions
    optax 0.1.0 depends on typing-extensions~=3.10.0
    flax 0.5.0 depends on typing-extensions>=4.1.1
    huggingface-hub 0.1.0 depends on typing-extensions
    jax 0.3.0 depends on typing_extensions
    optax 0.0.91 depends on typing-extensions~=3.10.0
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37
    optax 0.0.5 depends on jaxlib>=0.1.37
    optax 0.0.3 depends on jaxlib>=0.1.37
    optax 0.0.2 depends on jaxlib>=0.1.37
    optax 0.0.1 depends on jaxlib>=0.1.37`

**Comment by Talkashie** [comment]
Is there any solution to this? I'm also getting stuck here.

```
ERROR: Cannot install -r requirements.txt (line 4), flax and transformers because these package versions have conflicting dependencies.

The conflict is caused by:
    optax 0.1.2 depends on jaxlib>=0.1.37
    optax 0.1.1 depends on jaxlib>=0.1.37
    flax 0.5.0 depends on typing-extensions>=4.1.1
    huggingface-hub 0.1.0 depends on typing-extensions
    jax 0.3.0 depends on typing_extensions
    optax 0.1.0 depends on typing-extensions~=3.10.0
    flax 0.5.0 depends on typing-extensions>=4.1.1
    huggingface-hub 0.1.0 depends on typing-extensions
    jax 0.3.0 depends on typing_extensions
    optax 0.0.91 depends on typing-extensions~=3.10.0
    optax 0.0.9 depends on jaxlib>=0.1.37
    optax 0.0.8 depends on jaxlib>=0.1.37
    optax 0.0.6 depends on jaxlib>=0.1.37
    optax 0.0.5 depends on jaxlib>=0.1.37
    optax 0.0.3 depends on jaxlib>=0.1.37
    optax 0.0.2 depends on jaxlib>=0.1.37
    optax 0.0.1 depends on jaxlib>=0.1.37

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by karyeet** [comment]
I recommend just installing on WSL2 if you wish to use windows. The install will complete without issue.

**Comment by gadams999** [comment]
@karyeet I've got it working in WSL2 too, but realized I don't have access to all GPU RAM. Do you know what the system memory and GPU memory requirements are for Mega_full?

**Comment by karyeet** [comment]
@gadams999 
> Had to get cuda toolkit, cudnn, troubleshooting issues and stuff...but it's working great in WSL2.
> 
> Using mega model version takes ~30 seconds per image with Geforce GTX 1080, 32GB ram, Ryzen 5900X.

As dmwyatt points out, make sure you have the cuda toolkit and cudnn installed.
Also make sure you have jax[cuda] installed.

I could only run mini on 3060 6gb, [this post](https://huggingface.co/spaces/dalle-mini/dalle-mini/discussions/4) suggests you need at least 16gb of vram for mega_full.

Likely [8gb needed for mega](https://github.com/jina-ai/dalle-flow/issues/31#issuecomment-1160086257)

**Comment by mnai01** [comment]
> Any resolution for this? I cannot install tensorflowjs on my windows due to this.

Same exact problem when running `pip install tensorflowjs`

**Comment by reidpat** [comment]
I am sadly also having this error when trying to install tensorflowjs on my windows machine.

**Comment by saharmor** [comment]
@reidpat have you tried the solutions mentioned in this thread? If so, please paste the error you are getting

**Comment by yhann0827** [comment]
im also having the same error. anyone got any issues to solve this?

**Comment by AndreAlbu** [comment]
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
